# Generated by Django 5.1.7 on 2025-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('attendance', 'Attendance'), ('exams', 'Exams'), ('fees', 'Fees'), ('library', 'Library'), ('hostel', 'Hostel'), ('logical', 'Logical'), ('mathematics', 'Mathematics'), ('technical', 'Technical'), ('other', 'Other')], max_length=50),
        ),
    ]
