# Generated by Django 5.1.7 on 2025-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_student_roll_number_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='grade',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student', 'subject', 'semester', 'academic_year')},
        ),
    ]
